/**
 * Generate `src/core/pycase.ts`: where Python's case rules differ from the
 * JavaScript engine's, read from Python itself. Only the differences are kept,
 * so the table is small; `npm run parity:anonymise` checks the result against
 * Python for every code point.
 *
 *   node scripts/generate-pycase.ts          write the table
 *   node scripts/generate-pycase.ts --check  fail if it is out of date
 */

import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";

const OUT = new URL("../src/core/pycase.ts", import.meta.url);

type Ranges = [number, number][];
export interface PythonCaseData {
  version: string;
  lower: number[];
  cased: number[];
  fold: string[];
  extra: [number, number[]][];
  ranges: { word: Ranges; digit: Ranges; alpha: Ranges; upper: Ranges; unassigned: Ranges };
}

export function pythonCaseData(): PythonCaseData {
  return JSON.parse(
    execFileSync(
      "uv",
      [
        "run", "--quiet", "--project", "../core", "python", "-c",
        `
import json, sys, unicodedata, _sre
from re import _casefix
cps = [c for c in range(0x110000) if not 0xD800 <= c <= 0xDFFF]
def ranges(pred):
    out, start = [], None
    for c in range(0x110001):
        ok = c < 0x110000 and not 0xD800 <= c <= 0xDFFF and pred(chr(c))
        if ok and start is None: start = c
        if not ok and start is not None: out.append([start, c - 1]); start = None
    return out
print(json.dumps({
    "version": f"{sys.version_info.major}.{sys.version_info.minor} (Unicode {unicodedata.unidata_version})",
    "lower": [_sre.unicode_tolower(c) for c in cps],
    "cased": [int(_sre.unicode_iscased(c)) for c in cps],
    "fold": [chr(c).casefold() for c in cps],
    "extra": [[k, list(v)] for k, v in sorted(_casefix._EXTRA_CASES.items())],
    "ranges": {name: ranges(pred) for name, pred in {
        "word": lambda ch: ch.isalnum() or ch == "_", "digit": str.isdecimal, "alpha": str.isalpha,
        "upper": str.isupper, "unassigned": lambda ch: unicodedata.category(ch) == "Cn"}.items()},
}))
`,
      ],
      { encoding: "utf8", maxBuffer: 1 << 30 },
    ),
  );
}

/** The engine's single-character mapping, or the character itself if it maps to several. */
const single = (s: string, c: number) => ([...s].length === 1 ? s.codePointAt(0)! : c);

/** Ranges as base-36 deltas: "gap.length" per range, comma-separated. */
function encode(ranges: Ranges): string {
  let previous = -1;
  return ranges
    .map(([start, end]) => {
      const text = `${(start - previous - 1).toString(36)}.${(end - start).toString(36)}`;
      previous = end;
      return text;
    })
    .join(",");
}

export function render(data: PythonCaseData): string {
  const lower: [number, number][] = [];
  const casedDiffers: number[] = [];
  const fold: [number, string][] = [];
  let i = 0;
  for (let c = 0; c < 0x110000; c++) {
    if (c >= 0xd800 && c <= 0xdfff) continue;
    const ch = String.fromCodePoint(c);
    if (single(ch.toLowerCase(), c) !== data.lower[i]) lower.push([c, data.lower[i]]);
    const computedCased = data.lower[i] !== c || single(ch.toUpperCase(), c) !== c;
    if (computedCased !== (data.cased[i] === 1)) casedDiffers.push(c);
    if (ch.toLowerCase() !== data.fold[i]) fold.push([c, data.fold[i]]);
    i++;
  }
  const hex = (n: number) => `0x${n.toString(16)}`;
  const str = (s: string) => JSON.stringify(s).replace(/[^\x20-\x7e]/g, (ch) => `\\u${ch.charCodeAt(0).toString(16).padStart(4, "0")}`);
  const pairs = (xs: [number, number][]) => xs.map(([a, b]) => `[${hex(a)}, ${hex(b)}]`).join(", ");
  return `/**
 * Where Python's case rules differ from the JavaScript engine's, generated by
 * \`scripts/generate-pycase.ts\` from Python ${data.version}. Do not edit.
 *
 * - LOWER: the regular-expression engine's simple lowercase mapping
 *   (\`_sre.unicode_tolower\`) where it differs from \`toLowerCase()\` of one
 *   character (which gives the full mapping, sometimes several characters).
 * - CASED_DIFFERS: characters for which \`_sre.unicode_iscased\` differs from
 *   "its simple lowercase, or its one-character \`toUpperCase()\`, differs".
 * - FOLD: \`str.casefold()\` of one character where it differs from
 *   \`toLowerCase()\`.
 * - EXTRA_CASES: the lowercase letters Python's IGNORECASE also treats as
 *   equal (\`re._casefix\`), such as i and dotless ı.
 * - WORD, DIGIT, ALPHA, UPPER, UNASSIGNED: Python's \`\\w\`, \`\\d\`,
 *   \`isalpha()\`, \`isupper()\` and unassigned (Cn) characters, as ranges, so
 *   the rules don't change with the browser's Unicode version. Each range is
 *   "gap.length" in base 36, the gap counted from the end of the one before.
 */

export const LOWER = new Map<number, number>([${pairs(lower)}]);

export const CASED_DIFFERS = new Set<number>([${casedDiffers.map(hex).join(", ")}]);

export const FOLD = new Map<number, string>([${fold.map(([c, s]) => `[${hex(c)}, ${str(s)}]`).join(", ")}]);

export const EXTRA_CASES = new Map<number, number[]>([${data.extra.map(([k, v]) => `[${hex(k)}, [${v.map(hex).join(", ")}]]`).join(", ")}]);

export const WORD = "${encode(data.ranges.word)}";

export const DIGIT = "${encode(data.ranges.digit)}";

export const ALPHA = "${encode(data.ranges.alpha)}";

export const UPPER = "${encode(data.ranges.upper)}";

export const UNASSIGNED = "${encode(data.ranges.unassigned)}";
`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const text = render(pythonCaseData());
  if (process.argv.includes("--check")) {
    const same = readFileSync(OUT, "utf8") === text;
    console.log(same ? "pycase.ts is up to date" : "pycase.ts is out of date: run node scripts/generate-pycase.ts");
    process.exit(same ? 0 : 1);
  }
  writeFileSync(OUT, text);
  console.log(`wrote ${OUT.pathname}`);
}
