name = "feedbacker-worker"
# type = "service"
main = "src/index.ts"
compatibility_date = "2024-12-18"

# Cloudflare D1 binding
# binding = "DB"
[[d1_databases]]
binding = "feedbacker"
database_name = "feedbacker"
database_id = "39f9f0a6-eb9f-4f37-a396-9e6bd3d41211"

# Cloudflare Vectorize binding
[[vectorize]]
binding = "VECTORIZE"
index_name = "feedbacker-embeddings"

# Environment variables
[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }

# wrangler.toml CORS headers
# [[unsafe.bindings]]
# name = "ASSETS"
# type = "service"
# service = "feedbacker-assets"

# Steve - added to fix 'unsafe.bindings' warning generated above
[[services]]
binding = "ASSETS"
service = "feedbacker-assets"
